spring.application.name=payment-service
server.port=8084

# --- Quan trọng: Cấu hình Eureka ---
# Trỏ trực tiếp đến tên service discovery-server trong docker-compose
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# Giúp Eureka nhận diện bằng IP trong mạng Docker nội bộ
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.cloud.client.ip-address}:${server.port}

# --- Database Connection ---
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db-payment:5432/dhay_payment_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user_dhay}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password_dhay}
spring.jpa.hibernate.ddl-auto=update

# --- RabbitMQ ---
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:rabbitmq}
app.rabbitmq.payment-exchange=payment.exchange

# --- Bảo mật (Tạm thời tắt để Eureka đăng ký được) ---
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# 1. Giúp Swagger hiểu các cấu hình tùy chỉnh từ Bean OpenAPI của bạn
springdoc.override-with-generic-response=true

# 2. Quan trọng nhất: Giúp Service nhận diện được IP/Port của Gateway thay vì IP nội bộ Docker
server.forward-headers-strategy=framework

# 1. Giúp Swagger hiểu các cấu hình tùy chỉnh từ Bean OpenAPI của bạn
springdoc.override-with-generic-response=true

# 2. Quan trọng nhất: Giúp Service nhận diện được IP/Port của Gateway thay vì IP nội bộ Docker
server.forward-headers-strategy=framework