spring.application.name=payment-service
server.port=8084

# --- Database Connection ---
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/dhay_payment_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user_dhay}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password_dhay}
spring.jpa.hibernate.ddl-auto=update

# --- RabbitMQ ---
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
app.rabbitmq.payment-exchange=payment.exchange

# --- SERVICE DISCOVERY (EUREKA) ---
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

# --- Cấu hình gọi nội bộ (FeignClient) ---
# Dùng tên service để Eureka tự điều hướng
app.services.core-url=http://dhay-core-service
app.internal-api-key=dhay_secret_2026

# --- VNPay Config (Sửa Return URL về Gateway) ---
app.payment.vnpay.tmn-code=2QXUI4J4
app.payment.vnpay.secret-key=99999999999999999999999999999999
app.payment.vnpay.return-url=http://localhost:8080/api/v1/payments/vnpay-callback