# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: matching.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'matching.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ematching.proto\x12\x08matching\"L\n\x0cMatchRequest\x12\x0f\n\x07trip_id\x18\x01 \x01(\x03\x12\x16\n\x0eroute_polyline\x18\x02 \x01(\t\x12\x13\n\x0btotal_seats\x18\x03 \x01(\x05\"0\n\rMatchResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\\\n\x0fMatchingService\x12I\n\x16GetPotentialPassengers\x12\x16.matching.MatchRequest\x1a\x17.matching.MatchResponseB\x16\n\x12\x63om.duan.hday.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'matching_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.duan.hday.grpcP\001'
  _globals['_MATCHREQUEST']._serialized_start=28
  _globals['_MATCHREQUEST']._serialized_end=104
  _globals['_MATCHRESPONSE']._serialized_start=106
  _globals['_MATCHRESPONSE']._serialized_end=154
  _globals['_MATCHINGSERVICE']._serialized_start=156
  _globals['_MATCHINGSERVICE']._serialized_end=248
# @@protoc_insertion_point(module_scope)
