spring.application.name=discovery-server
server.port=8761

# Không đăng ký chính mình vào danh sách client
eureka.client.register-with-eureka=false
# Không cần tải danh sách service từ server khác (vì mình là server duy nhất)
eureka.client.fetch-registry=false

# Log cấu hình (tùy chọn để dễ debug)
logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF