spring.application.name=hday

# ===============================
# 1. DATABASE CONNECTION
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db-core:5432/hday_core_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user_hday}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password_hday}
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình Connection Pool (Hikari) - Giúp hệ thống chịu tải tốt hơn
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000

# ===============================
# 2. JPA / HIBERNATE CONFIGURATION
# ===============================
# Hibernate 6 tự động nhận diện Dialect, nên ta để Spring tự quyết định
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update

# Chiến lược đặt tên
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# Logging SQL (Chỉ bật khi thực sự cần debug trên máy cá nhân)
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# 3. JACKSON & TIMEZONE
# ===============================
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=Asia/Ho_Chi_Minh
# Ép toàn bộ ứng dụng chạy múi giờ VN để đồng bộ với DB và Mobile
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh

# ===============================
# 4. SERVLET & MULTIPART
# ===============================
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Chỉ để mức INFO cho production, DEBUG cho package của mình khi cần
logging.level.root=INFO
logging.level.com.duan.hday=DEBUG

# ===============================
# 5. FIREBASE
# ===============================
firebase.config-path=${FIREBASE_KEY_PATH:classpath:firebase-config-demo.json}

# JWT Configuration
app.jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
app.jwt.expiration=86400000

grpc.client.ai-matching.address=${GRPC_CLIENT_AI_SERVICE_ADDRESS:static://hday-ai-service:50051}
grpc.client.ai-matching.negotiation-type=plaintext